spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: hiRNqCJxtMbYkiOBZwKpOmHMKVeBgmkA
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    table: flyway_schema_history_auth

  security:
    oauth2:
      authorizationserver:
        # Це дозволить Auth Server самому знати своє ім'я в мережі Railway
        issuer: http://auth-server.railway.internal:9000