package ua.fpv;

public enum BotState {
    IDLE, AWAITING_SERIAL, AWAITING_COORDINATES, AWAITING_RESULT, AWAITING_FPV_DRONE,
    AWAITING_DATE_TIME_FLIGHT, AWAITING_ADDITIONAL_INFO, AWAITING_REB,
    AWAITING_VIDEO
}

