server:
  port: 8080

spring:
  datasource:
    # Використовуємо змінні з панелі Railway
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          # Внутрішня адреса Railway для спілкування між сервісами
          issuer-uri: http://auth-server.railway.internal:9000
          jwk-set-uri: http://auth-server.railway.internal:9000/oauth2/jwks

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true